from django.urls import path,include
from .views import recordView, studentView,classView , homeView , getClass, getRecord , getStudent , getClassRecord , getClassStudent,formView, searchView, addToRecord ,filterRecord,filterStudent,closeReq,generateReport,historyView,topicView,topicDetail,subjectView,subjectDetail,classTopic , addTopic,signUp,login, updateRecord,addStudent,addRecord
from .excel import export_report_excel

urlpatterns = [
    path("record", recordView,name="record-list"),
    path('student',studentView,name="student-list"),
    path('class',classView,name="class-list"),
    path('student/<int:id>',getStudent,name='get-student-detail'),
    path('class/<int:id>',getClass,name='get-class'),
    path('record/<int:id>',getRecord,name='get-record'),
    path('',homeView,name="home"),
    path('getclassrecord/<int:id>',getClassRecord,name="get-class-record"),
    path('getstudent/<int:id>',getClassStudent,name="get-student"),
    path('home/<str:part>',homeView,name='home-part'),
    path('form/<str:get_form>',formView,name="form"),
    path('search',searchView,name='search'),
    path('add-to-record/<int:id>',addToRecord,name='addToRecord'),
    path('filter-students',filterStudent,name="filterStudent"),
    path('filter-record',filterRecord,name="filterRecord"),
    path("close",closeReq,name="closeRequest"),
    path("generate-report",generateReport,name="generateReport"),
    path('history',historyView,name="historyView"),
    path("subjects",subjectView,name="subject-list"),
    path('topics',topicView,name="topic-list"),
    path('subject/<int:id>',subjectDetail,name="subject-detail"),
    path('topic/<int:id>',topicDetail,name="topic-detail"),
    path('classTopic/<int:id>/<str:name>',classTopic,name="class-topic"),
    path('addTopic/<int:id>',addTopic,name="add-topic"),
    path("signup",signUp,name="signup"),
    path("login",login,name="login"),
    path("update/<int:id>",updateRecord,name="update"),
    path('form/<str:get_form>/<int:update>',formView,name="update-form"),
    path('add-student/<int:id>',addStudent,name="add-student"),
    path('addrecord/<int:id>',addRecord,name="addRecord"),
    path('export-excel/',export_report_excel, name='export_report_excel'),
  ]