# Generated by Django 5.1.4 on 2025-04-16 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("First Term", "First Term"),
                            ("Second Term", "Second Term"),
                            ("Third Term", "Third Term"),
                        ],
                        max_length=10000,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "record_type",
                    models.CharField(
                        choices=[("Test", "Test"), ("Exam", "Exam")], max_length=1000000
                    ),
                ),
                ("total_score", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("JSS1", "JSS1"),
                            ("JSS2", "JSS2"),
                            ("JSS3", "JSS3"),
                            ("SS1", "SS1"),
                            ("SS2", "SS2"),
                            ("SS3", "SS3"),
                        ],
                        max_length=100000,
                    ),
                ),
                (
                    "batch",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=100000,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "batch")},
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100000)),
                (
                    "class_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to="record.class",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="record.record",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record",
                        to="record.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="record",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="record",
                to="record.subject",
            ),
        ),
    ]
