# Generated by Django 5.1.4 on 2026-06-21 00:32

import django.db.models.deletion
import record.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("JSS1", "JSS1"),
                            ("JSS2", "JSS2"),
                            ("JSS3", "JSS3"),
                            ("SS1", "SS1"),
                            ("SS2", "SS2"),
                            ("SS3", "SS3"),
                        ],
                        max_length=100000,
                    ),
                ),
                (
                    "batch",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=100000,
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        default=record.models.current_academic_session,
                        help_text="Academic session, e.g. 2025/2026",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=500, null=True)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(blank=True, max_length=500, null=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Teacher", "Teacher"),
                            ("School Administration", "School Administration"),
                            ("Student", "Student"),
                        ],
                        default="Teacher",
                        max_length=255,
                    ),
                ),
                ("secret_key", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="record.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=10000)),
                ("content", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(blank=True, null=True)),
                ("done", models.BooleanField(default=False)),
                (
                    "class_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic",
                        to="record.class",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic",
                        to="record.subject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="record.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubjectTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjectTeacher",
                        to="record.class",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjectTeacher",
                        to="record.subject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="record.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("subject", "class_name")},
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100000)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("admission_number", models.IntegerField(blank=True, null=True)),
                (
                    "contact_info",
                    models.CharField(blank=True, max_length=9000000, null=True),
                ),
                (
                    "date_of_birth",
                    models.CharField(blank=True, max_length=1000000, null=True),
                ),
                (
                    "class_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to="record.class",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Student",
                        to="record.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="record.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "class_name")},
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("First Term", "First Term"),
                            ("Second Term", "Second Term"),
                            ("Third Term", "Third Term"),
                        ],
                        max_length=10000,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("Test", "Test"),
                            ("Exam", "Exam"),
                            ("Assignment", "Assignment"),
                            ("Notes", "Notes"),
                        ],
                        max_length=1000,
                    ),
                ),
                ("total_score", models.IntegerField()),
                ("record_number", models.IntegerField(blank=True, null=True)),
                ("logic", models.CharField(blank=True, max_length=10000, null=True)),
                (
                    "auto_create_records",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically create student records when logic is present",
                    ),
                ),
                (
                    "show_in_report",
                    models.BooleanField(
                        default=True,
                        help_text="Indicate whether to include record in report ",
                    ),
                ),
                (
                    "class_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record",
                        to="record.class",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record",
                        to="record.subjectteacher",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="record.user",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("title", "subject", "class_name", "record_type", "record_number")
                },
            },
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000000, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("time", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="record.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="class",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_name",
                to="record.user",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="record.user",
            ),
        ),
        migrations.CreateModel(
            name="StudentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="record.record",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record",
                        to="record.student",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="record.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "record")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("user", "name", "batch", "session")},
        ),
    ]
