# Generated by Django 5.1.4 on 2026-06-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_term",
            field=models.CharField(
                blank=True,
                choices=[
                    ("First Term", "First Term"),
                    ("Second Term", "Second Term"),
                    ("Third Term", "Third Term"),
                ],
                default="First Term",
                max_length=100,
                null=True,
            ),
        ),
    ]
