# Generated by Django 5.1.4 on 2025-04-20 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="class_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="record",
                to="record.class",
            ),
        ),
    ]
