# Generated by Django 5.1.4 on 2026-07-17 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0002_user_active_term"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("First Term", "First Term"),
                            ("Second Term", "Second Term"),
                            ("Third Term", "Third Term"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "session",
                    models.CharField(help_text="e.g. 2025/2026", max_length=20),
                ),
                ("times_present", models.IntegerField(default=0)),
                ("times_absent", models.IntegerField(default=0)),
                (
                    "position_override",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "attentiveness",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "neatness",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "punctuality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "politeness",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "relationship_with_others",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("class_teacher_remark", models.TextField(blank=True, null=True)),
                ("hm_comment", models.TextField(blank=True, null=True)),
                (
                    "promoted_to",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("next_term_begins", models.DateField(blank=True, null=True)),
                (
                    "class_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_reports",
                        to="record.class",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_reports",
                        to="record.student",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="record.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "term", "session")},
            },
        ),
    ]
