# Generated by Django 5.1.4 on 2025-04-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0002_record_class_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="record_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name="record",
            unique_together={("title", "subject", "class_name", "record_type")},
        ),
        migrations.AlterUniqueTogether(
            name="studentrecord",
            unique_together={("student", "record")},
        ),
    ]
