# Generated by Django 5.1.4 on 2026-07-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0003_termreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="include_in_total",
            field=models.BooleanField(
                default=True,
                help_text="If unchecked, scores from this record are shown but excluded from total score and percentage in reports.",
            ),
        ),
    ]
