# Generated by Django 5.1.4 on 2025-04-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0003_record_record_number_alter_record_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="record",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="record",
            name="record_number",
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="record",
            unique_together={
                ("title", "subject", "class_name", "record_type", "record_number")
            },
        ),
    ]
