# Generated by Django 5.1.4 on 2025-06-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0004_alter_record_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000000)),
                ("url", models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=1000000, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("name", "class_name")},
        ),
    ]
