# Generated by Django 5.1.4 on 2026-07-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0004_record_include_in_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("Quiz", "Quiz"),
                    ("Test", "Test"),
                    ("Exam", "Exam"),
                    ("Assignment", "Assignment"),
                    ("Practical", "Practical"),
                    ("Worksheet", "Worksheet"),
                    ("Notes", "Notes"),
                ],
                max_length=1000,
            ),
        ),
    ]
