# Generated by Django 5.1.4 on 2025-06-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0005_history_alter_subject_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="history",
            name="title",
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name="history",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
