# Generated by Django 5.1.4 on 2025-06-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0007_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
