# Generated by Django 5.1.4 on 2025-06-12 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0008_alter_topic_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="class_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic",
                to="record.class",
            ),
        ),
    ]
