# Generated by Django 5.1.4 on 2025-06-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0009_topic_class_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="topic",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
