# Generated by Django 5.2 on 2025-07-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0011_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[('Test', 'Test'), ('Exam', 'Exam'), ('Assignment', 'Assignment'), ('Notes', 'Notes')], max_length=1000000),
        ),
    ]
