# Generated by Django 5.2 on 2025-08-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0013_class_user_history_user_record_user_student_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('School Administration', 'School Administration'), ('Student', 'Student')], default='Teacher'),
        ),
        migrations.AddField(
            model_name='user',
            name='school_name',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('user', 'name', 'batch')},
        ),
    ]
