# Generated by Django 5.2 on 2025-08-10 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0014_user_email_user_full_name_user_role_user_school_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_name', to='record.user'),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='contact_info',
            field=models.CharField(blank=True, max_length=9000000, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], null=True),
        ),
    ]
