# Generated by Django 5.2 on 2025-08-16 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0017_subjectteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='record.school'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectteacher',
            unique_together={('subject', 'class_name')},
        ),
    ]
