# Generated by Django 5.2 on 2025-08-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0018_student_school_alter_subjectteacher_unique_together'),
    ]

    operations = [
        # Temporarily make it IntegerField to avoid constraint issues
        migrations.AlterField(
            model_name='record',
            name='subject',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]