# Generated by Django 5.2 on 2025-08-18 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0020_auto_20250818_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='record.subjectteacher'),
        ),
    ]
