# Generated by Django 5.2 on 2025-10-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0021_alter_record_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('School Administration', 'School Administration'), ('Student', 'Student')], default='Teacher', max_length=255),
        ),
    ]
