# Generated by Django 5.2 on 2025-10-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0022_alter_record_record_number_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='logic',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[('Test', 'Test'), ('Exam', 'Exam'), ('Assignment', 'Assignment'), ('Notes', 'Notes')], max_length=1000),
        ),
    ]
