# Generated by Django 5.2 on 2025-10-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0023_record_logic_alter_record_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='auto_create_records',
            field=models.BooleanField(default=True, help_text='Automatically create student records when logic is present'),
        ),
    ]
