# Generated by Django 5.2 on 2025-10-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0024_record_auto_create_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='show_in_report',
            field=models.BooleanField(default=True, help_text='Indicate whether to include record in report '),
        ),
    ]
